project:
  type: manuscript

manuscript:
  article: MANUSCRIPT.qmd

execute:
  freeze: auto


format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx:
    toc: true
  jats: default
  agu-pdf: default

crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure


