project:
  type: manuscript

manuscript:
  article: MANUSCRIPT.qmd

execute:
  freeze: auto
  
notebook-links: false

format:
  html:
    toc: true
  docx:
    toc: true
  agu-pdf:
    default: true
  jats: 
    default: true

crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
