project:
  type: manuscript

manuscript:
  article: elsevier_MANUSCRIPT.qmd

execute:
  freeze: auto
  
notebook-links: false

format:
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Journal of Hydrology
      formatting: preprint
      model: 1p
      layout: onecolumn
      cite-style: authoryear
  html:
    toc: true
  docx:
    toc: true
  agu-pdf:
    default: true
  jats: 
    default: true
    
crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
