---
title: Regional-scale Base-flow Index of Gauged and Ungauged Basins in Drylands
author:
  - name: Caelum Mroczek
    orcid: 0009-0005-6695-0134
    corresponding: true
    email: csm428@nau.edu
    roles:
      - Conceptualization
      - Investigation
      - Methodology
      - Formal analysis
      - Visualization
      - Software
      - Data curation
      - Writing - Original Draft
    affiliations:
      - School of Earth and Sustainability, Northern Arizona University, Flagstaff, AZ, USA
      
  - name: Abraham Springer
    orcid: 0000-0003-4826-9124
    corresponding: false
    roles:
      - Conceptualization
      - Supervision
      - Project administration
      - Funding acquisition
    affiliations:
      - School of Earth and Sustainability, Northern Arizona University, Flagstaff, AZ, USA
      
  - name: Benjamin Lucas
    orcid: 0000-0002-2021-3076
    corresponding: false
    roles:
      - Software
      - Supervision
    affiliations:
      - Department of Mathematics and Statistics, Northern Arizona University, Flagstaff, AZ, USA
      
keywords:
  - Base Flow
  - Base-flow Index
  - Regionalization
  
abstract: |
  In September 2021, ...
plain-language-summary: |
  Earthquake data for the island of La Palma from the September 2021 eruption is found ...
  
key-points:
  - Base flow sustains dryland river ecology, but assessing its groundwater contribution faces data limitations
  - Recursive filtering and machine learning predict BFI and streamflow-associated recharge
  
date: last-modified
bibliography: references.bib
citation:
  container-title: Earth and Space Science
number-sections: true
---

## Introduction {#sec-intro}

Dryland regions, encompassing arid, semi-arid, hyper-arid, and dry sub-humid systems, account for 40% of the Earth’s land surface. They are home to approximately 2 billion people worldwide and represent the largest terrestrial biome (**iucn-drylands-2019)**. Despite supporting diverse ecosystems and human populations, dryland regions face mounting challenges exacerbated by increasing urbanization, expanding agricultural activities, and climate-induced amplification of precipitation patterns [@taylor2013]. This water scarcity is intensifying due to the compounding effects of climate variability and increased groundwater extraction [@taylor2013]. In drylands, groundwater serves as a vital resource for sustaining ecosystems and meeting human needs [@scanlon2006; @yao2018].

Base flow is the sustained portion of streamflow in the absence of runoff that is derived from groundwater discharge **(usgs-glossary-2018).** Base flow is critical to maintaining seasonal low-flow regimes, supporting aquatic ecosystems, and facilitating the transport of nutrients and chemicals. Base-flow contribution to streamflow can be highly variable spatially [@singh2018; @bosch2017; @beck2013], and temporally [@ficklin2016; @tan2020]. Increasing groundwater extraction, changes in land cover/land use, and changes in precipitation patterns due to climate change affect the timing and volumes of base flow [@tan2020; @taylor2013]. Effective management of water quantity and quality depends on understanding seasonal and interannual base flow patterns and long-term changes in base flow behavior.

## Data & Methods {#sec-data-methods}

## Conclusion {#sec-conclusion}

## References {.unnumbered}

::: {#refs}
:::
